version: '3.2'

services:
  ipxe:
    build:
      context: ./
    image: ipxe
    volumes:
      - type: bind
        source: ./compile
        target: /compile
      - type: bind
        source: ./ipxe.local
        target: /opt/ipxe.local
    labels:
      - "namespace=ipxe"
    container_name: ipxe
    environment:
      - ENV_BUILD=make everything
#      - ENV_EMBEDD=/compile/ipxe/src/config/local/ipxescript
#      - ENV_DEBUG=scsi,iscsi
